// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    RiGithubLine: typeof import('~icons/ri/github-line')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    RiTwitterLine: typeof import('~icons/ri/twitter-line')['default']
  }
}

export { }
